### ISSUE TITLE
curl报错 但运行两遍之后又莫名其妙连上了

### ISSUE THREAD

**Issue by pea4** [pd12bbf7608ae1/NUISTNet#1]
> root@MiRouter:# sh /root/nuistnet.sh
> 测试网络通断...
> 网络断开，尝试连接登录服务器...
> 获取当前登录信息...
> 获取本地IP...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    35  100    35    0     0   7000      0 --:--:-- --:--:-- --:--:--  8750
> IP获取成功
> 地址: 10.11.192.242
> /root/nuistnet.sh: line 201: iconv: not found
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   138    0     0  100   138      0   2029 --:--:-- --:--:-- --:--:--  2059
> curl: (23) Failed writing body (0 != 241)
> curl 错误 Code:127
> 未知情况，默认断网处理
> 获取本地IP...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    35  100    35    0     0   3888      0 --:--:-- --:--:-- --:--:--  4375
> IP获取成功
> 地址: 10.11.192.242
> /root/nuistnet.sh: line 102: iconv: not found
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   130    0     0  100   130      0   1625 --:--:-- --:--:-- --:--:--  1645
> curl: (23) Failed writing body (0 != 243)
> curl 错误 Code:127
> 使用硬编码ID
> 获取本地IP...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    35  100    35    0     0   3181      0 --:--:-- --:--:-- --:--:--  3500
> IP获取成功
> 地址: 10.11.192.242
> 尝试登录...
> /root/nuistnet.sh: line 152: iconv: not found
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   129    0     0  100   129      0    358 --:--:-- --:--:-- --:--:--   357
> curl: (23) Failed writing body (0 != 65)
> curl 错误 Code:127
> root@MiRouter:# sh /tmp/nuistnet.sh
> 测试网络通断...
> 网络断开，尝试连接登录服务器...
> 获取当前登录信息...
> 获取本地IP...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    35  100    35    0     0   5833      0 --:--:-- --:--:-- --:--:--  7000
> IP获取成功
> 地址: 10.11.192.242
> /tmp/nuistnet.sh: line 201: iconv: not found
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   138    0     0  100   138      0   2705 --:--:-- --:--:-- --:--:--  2760
> curl: (23) Failed writing body (0 != 241)
> curl 错误 Code:127
> 未知情况，默认断网处理
> 获取本地IP...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    35  100    35    0     0   2692      0 --:--:-- --:--:-- --:--:--  2916
> IP获取成功
> 地址: 10.11.192.242
> /tmp/nuistnet.sh: line 102: iconv: not found
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   130    0     0  100   130      0   1585 --:--:-- --:--:-- --:--:--  1585
> curl: (23) Failed writing body (0 != 243)
> curl 错误 Code:127
> 使用硬编码ID
> 获取本地IP...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    35  100    35    0     0   3888      0 --:--:-- --:--:-- --:--:--  4375
> IP获取成功
> 地址: 10.11.192.242
> 尝试登录...
> /tmp/nuistnet.sh: line 152: iconv: not found
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   129    0     0  100   129      0   1869 --:--:-- --:--:-- --:--:--  1897
> curl: (23) Failed writing body (0 != 248)
> curl 错误 Code:127
> root@MiRouter:~# sh /tmp/nuistnet.sh
> 测试网络通断...
> 已经联网，退出

第一次失败我以为是root文件夹权限问题就转移到了tmp，运行前都给nuistnet.sh了777权限，不太清楚是不是我路由器环境的问题

**Comment by pd12bb** [comment]
问题应该是出在路由器的运行环境上，缺少了iconv这个命令(由于学校的API采用GB2312编码，使用iconv统一为UTF-8编码)导致从学校API取得的数据无法分析导致的报错，但实际请求已经发送给了学校的API，所以是登录成功的。你可以试着用bash运行，或者使用接入路由器的设备运行（我跑在树莓派上），或者干脆无视这个错误。
数据分析主要用于当前登录情况的查询，以后学校API的变更之类的，在不可用的时候会使用内置的硬编码数据（以后学校更改了配置可能要改）。
