### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by wwwmmwww** [pd12bbf7608ae1/NUISTNet#3]
你好，假设我想做宽带聚合，可不可以用这个做到

**Comment by pd12bb** [comment]
这个脚本只能解决上网账号的登录问题，你需要自己实现宽带聚合，然后使用这个脚本分别登录多个网络，这时候使用 sourceip 版本的可能有助于使用。
实现宽带聚合可以尝试 iKuai OpenWRT 等路由器系统，具体使用方法还得自己琢磨
